// This file has been generated by Tauri Specta. Do not edit this file manually.
/**
	* @typedef {({ Study: StudyArgs }) & { Rest?: never } | ({ Rest: RestArgs }) & { Study?: never } | "AFK"} PomoType
	* @property {{ Study: StudyArgs }} Study
	* @property {{ Rest: RestArgs }} Rest
	* @property {"AFK"} AFK
	*
	* @typedef {{
	*		seconds: number,
	*		name: string,
	*	}} RestArgs
	* @property {number} seconds
	* @property {string} name
	*
	* @typedef {{
	*		seconds: number,
	*		name: string,
	*	}} StudyArgs
	* @property {number} seconds
	* @property {string} name
	*/
