// This file has been generated by Tauri Specta. Do not edit this file manually.
/**
	*  You will receive this event when someone joins your pomodoro
	*
	* @typedef {null} JoinEvent
	*
	* @typedef {{
	*		host: boolean,
	*		time: number,
	*	}} Message
	* @property {boolean} host
	* @property {number} time
	*
	*  You will receive this event when someone messages in the pomodoro (not host specific)
	*
	* @typedef {Message} MessageEvent
	* @property {Message} "0"
	*/
