// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 * @param {string} name
	 * @returns {Promise<string>}
	 */
	greet: (name) => __TAURI_INVOKE("greet", { name }),
	/** @returns {Promise<number>} */
	createTimer: () => __TAURI_INVOKE("create_timer"),
	/**
	 * @param {number} index
	 * @returns {Promise<number>}
	 */
	getTimer: (index) => __TAURI_INVOKE("get_timer", { index }),
	/**
	 * @param {string} room
	 * @returns {Promise<{ status: "ok"; data: null } | { status: "error"; error: string }>}
	 */
	host: (room) => typedError(__TAURI_INVOKE("host", { room })),
	/**
	 * @param {string} room
	 * @returns {Promise<{ status: "ok"; data: null } | { status: "error"; error: string }>}
	 */
	join: (room) => typedError(__TAURI_INVOKE("join", { room })),
	/**
	 * @param {string} message
	 * @returns {Promise<{ status: "ok"; data: null } | { status: "error"; error: string }>}
	 */
	sendmessage: (message) => typedError(__TAURI_INVOKE("sendmessage", { message })),
	/** @returns {Promise<string | null>} */
	receivemessage: () => __TAURI_INVOKE("receivemessage"),
};

/* Tauri Specta runtime */
/**
  * @template T
  * @template E
  * @param {Promise<T>} result
  * @returns {Promise<{ status: "ok"; data: T } | { status: "error"; error: E }>}
  */
async function typedError(result) {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e };
    }
}
